### PR TITLE
AmazFit_Watchface_Editor 8.5 - Italian language update

### PR DESCRIPTION
**Pull request by bovirus**
@SashaCX75 

Please check and if you can merge. Thanks.

### CODE REVIEW

**Comment by SashaCX75** [comment]
I work with the dev branch and the changes you make to the master branch do not appear in the program.
I don’t know how you edit the file, but I don’t see what changes have been made to the file, I can only see what files have changed. Therefore, I cannot transfer changes to the current file. I will not completely copy the changed file to the dev branch, because there may be a newer version of the file in it.

Я работаю с веткой dev и изменения которые ты вносишь в ветку master не появляются в программе.
Не знаю как ты редактируешь файл, но мне не видно какие изменения внесены в файл, видно только какие файлы изменились. Поэтому я не могу перенести изменения в текущий файл. Полностью копировать измененный файл в ветку dev я не буду, потому что в ней может находиться более новая версия файла.

**Comment by bovirus** [comment]
I used "Resxtranslator" application to compare and edit the files.

What kind of error you get?

**Comment by SashaCX75** [comment]
There are no errors, only you cannot see what exactly has changed in the file. Indicates that the entire file has been modified.
I will remember that the files you changed were not changed in the dev branch. Therefore, I will move them to the dev branch, replacing the files there.

Next time, change the files in the dev branch, there are the latest versions of the files.

**Comment by bovirus** [comment]
@SashaCX75 

Sorry for my error. I agree with you.
I didn't check and I made the changes in master (final) branch instead on "dev" (beta) branch.
Sorry again for my error.

Thanks.

**Comment by SashaCX75** [comment]
It's just that new versions have new phrases that do not yet have a translation. I think it's more important to add a missing translation than to improve an existing one.

**Comment by SashaCX75** [comment]
The problem is that not seeing what exactly has changed in the file, I have to look through all the tabs to see how the new translation fits into the interface. I can miss something and not notice that some kind of inscription did not fit and it must be moved.

**Pull request merged**
