### PR TITLE
Add strings to English and Italian

### PR DESCRIPTION
**Pull request by bovirus**
@SashaCX75 

Please check and merge.
If you can when you add new struing as master in Russian please add also relatiev strings in English.
Thanks.

### CODE REVIEW

**Comment by SashaCX75** [comment]
I don’t know what exactly you did differently this time, but now I can see what exactly changed in the file. It's much more convenient for me to check for updates.

There are still some new lines with new messages left not translated in the AmazFit_Watchface_Editor / GTR_Watch_face / Properties / FormStrings.it.resx file

**Comment by SashaCX75** [comment]
[https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v9.0-beta](url)
Fixed Italian interface due to translation editing.

It seems that I checked everything, but check it yourself, maybe I missed some elements and they overlapped each other due to the difference in the length of the inscriptions in different languages.

**Comment by bovirus** [comment]
@SashaCX75 

If I click on  the link on your post 

https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v9.0-beta

it point to

https://github.com/SashaCX75/AmazFit_Watchface_Editor/pull/url

and report 404 file not found.

**Comment by SashaCX75** [comment]
The link works for me.
Try this link
[v9.0-beta](/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v9.0-beta)

**Comment by bovirus** [comment]
Infact the link

https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v9.0-beta

works fine and I downloaded the file.

On 3. post please move mouse over link and you can see the link

https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v9.0-beta

point really to

https://github.com/SashaCX75/AmazFit_Watchface_Editor/pull/url

that didn't work.

Just for your info.

**Pull request merged**
