### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@SashaCX75 

Cleanup not necessary strings
Add new strings
Translated new strings.

Pelase check and update.

Thanks.

### CODE REVIEW

**Comment by SashaCX75** [comment]
This editor is no longer supported by me. I updated the translation files, but didn't check.
[AmazFit_Watchface_Editor_(without_Python)_10_0.zip](https://github.com/SashaCX75/AmazFit_Watchface_Editor/files/6954056/AmazFit_Watchface_Editor_.without_Python._10_0.zip)

**Comment by bovirus** [comment]
@SashaCX75 

Thansk for the update.

Amazfix Watch Editor v2

https://github.com/SashaCX75/AmazFit_Watchface_Editor_2

does support also Amazfit watches supported by this version (v1)?

Plese when you can relase a new build for v2.

**Comment by SashaCX75** [comment]
@bovirus 
AmazFit WatchFace editor 2 supports watch faces from GTR 2 (e), GTS 2 (GTS 2e / Zepp E Square), T-Rex Pro, Zepp E Circle.

The format of the dials is different there, so the dials made in different versions of the editor are not compatible.

**Comment by bovirus** [comment]
Then the Watchface editor for old watches (execpt GTR 2 (e), GTS 2 (GTS 2e / Zepp E Square), T-Rex Pro, Zepp E Circle) was EOL (End of Life).

Then you will continue to improve the v2 that is only for GTR 2 (e), GTS 2 (GTS 2e / Zepp E Square), T-Rex Pro, Zepp E Circle.

Thanks.

**Pull request merged**
