### PR TITLE
Italian language update

### PR DESCRIPTION
**Pull request by bovirus**
@SashaCX75 

Italian language update.
Please check and merge.
Thanks.

### CODE REVIEW

**Comment by SashaCX75** [comment]
The latest version has new elements in the main window (in the settings and displaying the distance)

**Comment by bovirus** [comment]
@SashaCX75

Are there other resource that I have to check/translate?
In which place?

**Comment by SashaCX75** [comment]
I don't know how you edit the translation, so I don't know how best to explain where the translation is missing. Highlight the right place on the screenshot or name a file with incomplete translation?

**Comment by bovirus** [comment]
@SashaCX75 

I open .res file (master and Italian) with Zeta Resource Editor.
ZRE showed in column the master/translation stringsand highlight missing translattion.
I found that vs previous version there are few new string (less than 10).
 When you posted that you have new elements in main window I beleieve that you added after my latest changes (PR).

**Pull request merged**
